[package]
name = "tachyon"
version = "0.0.0"
edition = "2024"
rust-version = "1.90.0"
description = "The Tachyon shielded transaction protocol (stub)"
readme = "README.md"
categories = ["cryptography::cryptocurrencies"]
keywords = ["zcash", "tachyon"]

[dependencies]
serde = { workspace = true }
core2 = { version = "0.3", default-features = false, features = ["alloc"] }

# Cryptographic primitives
addchain = { git = "https://github.com/ebfull/addchain", rev = "da4099a81bc29c895f3ca0ebcaae21c860494c12" }
ff = { git = "https://github.com/ebfull/ff", rev = "e46e1d268bc026708c8ddeb2d49766ea49f9e70e" }
pasta_curves = { git = "https://github.com/ebfull/pasta_curves", rev = "32152d552b1c39fb3ffab8f0d8646f946c4adecc" }
rand.workspace = true
reddsa.workspace = true
bitvec.workspace = true
sinsemilla = "0.1.0"
blake2b_simd.workspace = true
ragu_pcd = { git = "http://github.com/tachyon-zcash/ragu", version = "0.0.0" }
ragu_gadgets = { git = "http://github.com/tachyon-zcash/ragu", version = "0.0.0" }
ragu_primitives = { git = "http://github.com/tachyon-zcash/ragu", version = "0.0.0" }
ragu_core = { git = "http://github.com/tachyon-zcash/ragu", version = "0.0.0" }
ragu_pasta = { git = "http://github.com/tachyon-zcash/ragu", version = "0.0.0" }
ragu_arithmetic = { git = "http://github.com/tachyon-zcash/ragu", version = "0.0.0" }

[dev-dependencies]
proptest = { workspace = true }

[lib]
bench = false

[features]
default = ["std"]
std = ["core2/std"]
